apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  serviceName: "mosquitto"
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto-test-2
        image: eclipse-mosquitto:latest
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: mosquitto-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          readOnly: true
      volumes:
      - name: mosquitto-config
        configMap:
          name: mosquitto-config
          items:
            - key: "mosquitto.conf"
              path: "mosquitto.conf"