apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    user mosquitto

    allow_anonymous true
    allow_duplicate_messages false
    connection_messages true
    log_dest stdout
    log_timestamp true
    log_type all
    persistence false

    port 1883

    