apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  # clusterIP: None
  selector:
    app: mosquitto
  ports:
  - name: port1883
    port: 1883
    targetPort: 1883
    protocol: TCP
    
  