apiVersion: v1
kind: Service
metadata:
  name: populator-api
spec:
  # clusterIP: None
  selector:
    app: populator-api
  ports:
  - name: port8085
    port: 8085
    targetPort: 8085
    protocol: TCP
---    
apiVersion: v1
kind: Service
metadata:
  name: arango
spec:
  # clusterIP: None
  selector:
    app: arango
  ports:
  - name: port8529
    port: 8529
    targetPort: 8529
    protocol: TCP
