apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: ali
subjects:
- kind: ServiceAccount
  name: onboarder
  namespace: ali
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
