---

- hosts: 127.0.0.1
  gather_facts: false
  vars:
    agent_binary_path: na
    systemd_unit_path: na
    dcf_config: "{{ dcf_config }}"
    onboarder_url: "{{ onboarder_url }}"
  tasks:
    - name: "Copy DCF agent binary"
      copy:
        # src: /root/dev/CLEVER/secure-onboarding/onboarding/dcfagent
        src: "{{ agent_binary_path }}"
        dest: /tmp/dcfagent
        mode: 0755

    - name: "Copy dcfagent systemd file"
      template:
        src: "{{ systemd_unit_path }}"
        dest: /etc/systemd/system/dcfagent.service
        owner: root
        mode: 0644

    - name: "Copy signautre private key"
      copy:
        src: "{{ private_key }}"
        dest: /tmp/private.key
        mode: 0644


    - name: "Copy config file"
      copy:
        src: "{{ dcf_config }}"
        dest: /tmp/config.json
        mode: 0644

    - name: "Stop DCF Agent daemon if running"
      systemd:
        name: dcfagent
        state: stopped 
        enabled: True
        daemon_reload: True

    - name: "Start DCF Agent daemon"
      systemd:
        name: dcfagent
        state: started
        enabled: True
        daemon_reload: True
